test "item flags of item":
    set {_i} to unbreakable itemstack of diamond sword with hide unbreakable itemflag
    assert size of (item flags of {_i}) = 1 with "size of item flags should have been 1"
    assert item flags of {_i} contains hide unbreakable with "item flags of item should have 'hide_unbreakable'"

    enchant {_i} with sharpness 10
    add hide enchants to item flags of {_i}
    assert size of (item flags of {_i}) = 2 with "size of item flags should have been 2"

    remove hide unbreakable and hide enchants from item flags of {_i}
    assert size of (item flags of {_i}) = 0 with "size of item flags should have been 0"
