test "SkBee - chunk stuff":

    # Test that these syntaxes don't cause errors
    set {_l} to location(500,100,500)

    load chunk at {_l} with ticket
    assert chunk at {_l} is loaded with "Chunk at location should be loaded"

    # Can't test this, need a wait after chunk is unloaded to test
    #unload chunk at {_l}
    #assert chunk at {_l} is not loaded with "Chunk at location should have unloaded"
